/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package charbol;

import javax.swing.JOptionPane;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Raul
 */
public class PreguntasRespuestas extends javax.swing.JFrame {
    private static Arbol obj = new Arbol();
    private static ArbolDir objDir = new ArbolDir();
    private static CreateJson objSaludo = new CreateJson();
    private static CreateJson objPrecio = new CreateJson();
    private static CreateJson objProducto = new CreateJson();
    private static String DirObjSaludo = "Saludos.json";
    private static String DirObjPrecio = "Precios.json";
    private static String DirObjProducto = "Productos.json";
    private static String posibleQuestion ="";
    private static String posibleAnswer = "";
    
    /**
     * Creates new form PreguntasRespuestas
     */
    public PreguntasRespuestas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJsons = new javax.swing.ButtonGroup();
        txtQuestion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAnswer = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jRadioButtonSaludos = new javax.swing.JRadioButton();
        jRadioButtonPrecios = new javax.swing.JRadioButton();
        jRadioButtonProductos = new javax.swing.JRadioButton();
        btnBackToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestionActionPerformed(evt);
            }
        });

        jLabel1.setText("Pregunta");

        jLabel2.setText("Respuesta");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        buttonGroupJsons.add(jRadioButtonSaludos);
        jRadioButtonSaludos.setText("Saludos");

        buttonGroupJsons.add(jRadioButtonPrecios);
        jRadioButtonPrecios.setText("Precios");

        buttonGroupJsons.add(jRadioButtonProductos);
        jRadioButtonProductos.setText("Productos");

        btnBackToMenu.setText("Back to Menu");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonSaludos)
                            .addComponent(jRadioButtonPrecios)
                            .addComponent(jRadioButtonProductos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackToMenu)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jRadioButtonSaludos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPrecios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnBackToMenu))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Método para ingresar preguntas con posibles respuestas
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        posibleQuestion = txtQuestion.getText().replaceAll("[^a-zA-Z0-9]+","");
        posibleAnswer = txtAnswer.getText().replaceAll("[^a-zA-Z0-9]+","");
        /*if(jRadioButtonSaludos.isSelected()){
            objSaludo.setObj(posibleQuestion, posibleAnswer);
            objSaludo.FlushFile(DirObjSaludo);
          
            obj.agregarNodo(3, objSaludo);
        }if(jRadioButtonPrecios.isSelected()){
            objPrecio.setObj(posibleQuestion, posibleAnswer);
            objPrecio.FlushFile(DirObjPrecio);
            
            obj.agregarNodo(4, objPrecio);
        }
        if(jRadioButtonProductos.isSelected()){
            objProducto.setObj(posibleQuestion, posibleAnswer);
            objProducto.FlushFile(DirObjProducto);
           
            obj.agregarNodo(2, objProducto);
        }*/
        
        if(jRadioButtonSaludos.isSelected()){
            String dirSaludo = "Saludos.txt";
            escribirArchivo(dirSaludo,posibleQuestion,posibleAnswer);
        }
        
        if(jRadioButtonPrecios.isSelected()){
            String dirPrecio = "Precios.txt";
            escribirArchivo(dirPrecio,posibleQuestion,posibleAnswer);
        }
        
        if(jRadioButtonProductos.isSelected()){
            String dirProducto = "Productos.txt";
            escribirArchivo(dirProducto,posibleQuestion,posibleAnswer);
        }
        
        txtQuestion.setText("");
        txtAnswer.setText("");
        txtQuestion.requestFocus();
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu irMenu = new Menu();
        irMenu.setVisible(true);
        irMenu.pack();
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void txtQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreguntasRespuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreguntasRespuestas().setVisible(true);
            }
        });
    }
    //Metodo testing no usar mas
    public static void recorridoInOrden(){
        if(!obj.verificarVacio()){
            obj.inOrden(obj.getRaiz());
        }else{
            JOptionPane.showMessageDialog(null, "El arbol esta vacío");
        }
    }
    //Metodo testing no usar mas
    public static void recorridoPreOrden(){
        if(!objDir.verificarVacio()){
            objDir.preOrden(objDir.getRaiz());
        }else{
            JOptionPane.showMessageDialog(null, "El arbol esta vacío!");
        }
    }
    //Metodo Indispensable
    public static void escribirArchivo(String dir,String quest,String answ){
        File archivo;
        FileWriter escribir;
        PrintWriter linea;
        
        archivo = new File(dir);//tiene que tener .txt
        if(!archivo.exists()){
            try {
                archivo.createNewFile();
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                //Escritura en el archivo
                linea.println(quest);
                linea.println(answ);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(PreguntasRespuestas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                
                escribir = new FileWriter(archivo,true);
                linea = new PrintWriter(escribir);
                //Escritura en el archivo
                linea.println(quest);
                linea.println(answ);
                linea.close();
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(PreguntasRespuestas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnIngresar;
    private javax.swing.ButtonGroup buttonGroupJsons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonPrecios;
    private javax.swing.JRadioButton jRadioButtonProductos;
    private javax.swing.JRadioButton jRadioButtonSaludos;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtQuestion;
    // End of variables declaration//GEN-END:variables
}
